a=int(input("Enter the value of A : "))
b=int(input("Enter the value of B : "))
print("Sum            : ",a+b)
print("Difference     : ",a-b)
print("Product        : ",a*b)
print("Division       : ",a/b)
print("Floor division : ",a//b)
print("Modulus        : ",a%b)
print("Exponent       : ",a**b)
