a=int(input("Enter the value of A : "))
b=int(input("Enter the value of B : "))
print("A & B : ",a & b)
print("A | B : ",a | b)
print("A ^ B : ",a ^ b)
print("~A    : ",~a)
print("~B    : ",~b)
print("A >> B : ",a>>b)
print("A << B : ",a<<b)
print("B >> A : ",b>>a)
print("B << A : ",b<<a)

